[package]
name = "glue_media"
version = "0.1.0"
edition = "2021"

[dependencies]
glue_traits = { path = "../traits" }
thiserror = "2.0.3"
serde = { version = "1.0.218", features = ["derive"] }
log = "0.4.26"
clap = { version = "4.5.30", features = ["derive"] }
